### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by miyalee** [weexteam/weex-builder#1]
使用weexpack的项目，在src中放了png， `npm run dev`时报错：
```
build failed!
[webpack errors]
./images/logo.login.png
You may need an appropriate loader to handle this file type.
```

这个要怎么修改？求解决

**Comment by erha19** [comment]
Upgrade your weex-toolkit.
If your npm < 5 ,please run `npm i npm@5 -g`.
If you use `cnpm`, please change to `nrm` to menage your npm origin.
```
rm -rf ~/.xtoolkit
npm un weex-toolkit -g
npm i weex-toolkit -g
weex update weexpack
```
Then re-create your project and run `npm i && npm start`.
