### ISSUE TITLE
Why not upgrade to a higher version of webpack？

### ISSUE THREAD

**Issue by PerseveranceZ** [weexteam/weex-builder#8]
Why not upgrade to a higher version of webpack for reduce the volume of the js bundle and speed up the compilation speed with the latest features?

**Comment by erha19** [comment]
@PerseveranceZ https://github.com/weexteam/weex-builder/commit/e7392063e88c6635db262f2bc85050bf1f36d82c.
The `webpack` have been upgraded to `3.10.0`.

**Comment by PerseveranceZ** [comment]
awesome!!! I have another question. Is UI component library able to support tree-shaking? I have tried it, but weex-ui or other libraries are not supported at present. When I import some components, I will still pack it all in.
